name: API Tests
on:
  pull_request:
  push:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/api-tests.yml"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          pip install -r api/requirements.txt
          pip install -r api/requirements-dev.txt
          pytest -q
