name: SBOM & Vulnerability Scan
on: [push, pull_request]
jobs:
  scan:
    runs-on: ubuntu-latest
    permissions: { contents: read, security-events: write }
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0
        with: { artifact-name: sbom-spdx.json }
      - uses: anchore/scan-action@v4
        with: { fail-build: false, severity-cutoff: high }
