name: Stale
on:
  schedule:
    - cron: "0 3 * * 1"
permissions: { issues: write, pull-requests: write }
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-stale: 60
          days-before-close: 14
